### ISSUE TITLE
Issues with index.php

### ISSUE THREAD

**Issue by chistogo** [Zortrox/CS496-Project#14]
- Game buttons in join game menu are not needed
- Put the regular text outside the <i></i> tags in find game.  (Notice the font is not the same) 
- Game list carousel should not have static height. This will mess with different device sizes. Instead of using 600 px in the CSS try to use a unit like 70 vh (which means 70% of view port) 
- Should add a little vertical margin to shaking titles in both the Host and Join menu

**Comment by jaredprince** [comment]
Fixed all these.

**Comment by chistogo** [comment]
The main branch has not been updated with these changes

**Comment by chistogo** [comment]
Please see https://github.com/Zortrox/CS496-Project/blob/master/project/website/css/main.css

Line 46
